name: opencosmos
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - tqdm
  - colorlog
  - requests
  - pre-commit
  - pytest
  - click
  - sentinelhub
  - pip:
      - python-dotenv
      - Pillow
      - google-cloud-storage
      - matplotlib
      - rasterio
      - ipykernel
      - pandas
      - rio-cogeo